# Gunakan Python 3.10 atau versi terbaru yang stabil
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements.txt dan install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy seluruh source code
COPY src /app/src
COPY main.py /app/
COPY .env.example /app/

# Set environment variables
ENV PYTHONUNBUFFERED 1