# FILE: docker/prometheus.yml
global:
  # Scrape metrik setiap 5 detik
  scrape_interval: 5s
  external_labels:
    monitor: 'distributed-sync-monitor'

scrape_configs:
  # --- Node Lock Manager (Raft) ---
  - job_name: 'lock_nodes_metrics'
    static_configs:
      - targets: 
          # Menggunakan nama service Docker
          - 'node_lock_1:8001'
          - 'node_lock_2:8002'
          - 'node_lock_3:8003'
        labels:
          component: lock_manager
          
  # --- Node Cache Coherence (MESI) ---
  - job_name: 'cache_nodes_metrics'
    static_configs:
      - targets: 
          - 'node_cache_1:8021'
          - 'node_cache_2:8022'
          - 'node_cache_3:8023'
        labels:
          component: cache
          
  # --- Node Distributed Queue ---
  - job_name: 'queue_nodes_metrics'
    static_configs:
      - targets: 
          - 'node_queue_1:8011'
          - 'node_queue_2:8012'
          - 'node_queue_3:8013'
        labels:
          component: queue